# Generated by Django 2.2.2 on 2019-06-26 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=18)),
                ('two', models.CharField(max_length=18)),
                ('three', models.CharField(max_length=18)),
                ('four', models.CharField(max_length=18)),
                ('five', models.CharField(max_length=18)),
                ('six', models.CharField(max_length=18)),
                ('seven', models.CharField(max_length=18)),
                ('eight', models.CharField(max_length=18)),
                ('nine', models.CharField(max_length=18)),
                ('ten', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('top_colors', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='colors.ColorPalette')),
            ],
        ),
    ]
